from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 561))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setSpacing(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(660, 0, 160, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        ################# TEXT
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        ################# EDIT
        self.verticalLayout.addWidget(self.textEdit)
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setObjectName("EndTurnButton")
        self.loadbt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loadbt.setEnabled(True)
        self.loadbt.setObjectName("LoadGameButton")
        self.savebt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.savebt.setEnabled(True)
        self.savebt.setObjectName("SaveGameButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.savebt)
        self.verticalLayout.addWidget(self.loadbt)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_game = QtWidgets.QAction(MainWindow)
        self.actionSave_game.setObjectName("actionSave_game")
        self.actionLoad_game = QtWidgets.QAction(MainWindow)
        self.actionLoad_game.setObjectName("actionLoad_game")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuOptions.addAction(self.actionSave_game)
        self.menuOptions.addAction(self.actionLoad_game)
        self.menuOptions.addAction(self.actionExit)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "End turn"))
        self.loadbt.setText(_translate("MainWindow", "Load game"))
        self.savebt.setText(_translate("MainWindow", "Save game"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionSave_game.setText(_translate("MainWindow", "Save game"))
        self.actionLoad_game.setText(_translate("MainWindow", "Load game"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
